# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2e569d1b8b8e3bfccd6ce4ee136512e0"
application_url = "https://ins-basement-quickly-instructors.trycloudflare.com"
embedded = true
name = "DynasTea"
handle = "dynastea"

[build]
include_config_on_deploy = true
dev_store_url = "plant-dynasty.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_files"

[auth]
redirect_urls = ["https://ins-basement-quickly-instructors.trycloudflare.com/auth/callback", "https://ins-basement-quickly-instructors.trycloudflare.com/auth/shopify/callback", "https://ins-basement-quickly-instructors.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
