# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "eb6249d0c0963d48ea010542e40815f1"
application_url = "https://islands-middle-region-generic.trycloudflare.com"
embedded = true
name = "dynasTea"
handle = "dynastea"

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_files"

[auth]
redirect_urls = [
  "https://islands-middle-region-generic.trycloudflare.com/auth/callback",
  "https://islands-middle-region-generic.trycloudflare.com/auth/shopify/callback",
  "https://islands-middle-region-generic.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "plant-dynasty.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
